[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
; Database connection is configured via command line arguments
; and environment variables in docker-compose.yml
log_level = info
without_demo = True
proxy_mode = True
